#include "556RTx.h"
#include "init.h"
#include "commands.h"
#include "gpio.h"





void init_556RTx(void)
{

    SET_PIN(ADR0 , 0);
    SET_PIN(ADR1 , 0);
    SET_PIN(ADR2 , 0);
    SET_PIN(ADR3 , 0);
    SET_PIN(ADR4 , 0);
    SET_PIN(ADR5 , 0);
    SET_PIN(ADR6 , 0);
    SET_PIN(ADR7 , 0);
    SET_PIN(ADR8 , 0);
    SET_PIN(ADR9 , 0);
    SET_PIN(ADR10 , 0);

    SET_PIN(DATACTL0 , 0);
    SET_PIN(DATACTL1 , 0);
    SET_PIN(DATACTL2 , 0);
    SET_PIN(CE , 1);
    SET_PIN(ON12V , 0);

    CFG_PIN(ADR0, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR1, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR2, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR3, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR4, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR5, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR6, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR7, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR8, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR9, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ADR10, OUTPUT, PUSHPULL | SLOPE_2MHZ);

    CFG_PIN(DATACTL0, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(DATACTL1, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(DATACTL2, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(CE, OUTPUT, PUSHPULL | SLOPE_2MHZ);
    CFG_PIN(ON12V, OUTPUT, PUSHPULL | SLOPE_2MHZ);

    CFG_PIN(DATAIN, INPUT, FLOATING);
}
